#!/bin/sh
# Build a sideloadable Android APK (debug or signed release).
# Release APKs require a keystore — this script creates a local one if missing.
set -e

VARIANT="${1:-debug}"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
MOBILE_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
ANDROID_DIR="$MOBILE_DIR/android"
ROOT_DIR="$(CDPATH= cd -- "$MOBILE_DIR/../.." && pwd)"

if [ "$VARIANT" != "debug" ] && [ "$VARIANT" != "release" ]; then
  echo "Usage: $0 [debug|release]"
  exit 1
fi

if [ ! -d "$ANDROID_DIR" ]; then
  echo "Android project missing at $ANDROID_DIR"
  echo "Run: pnpm mobile:add-android && pnpm mobile:sync"
  exit 1
fi

if [ -z "$JAVA_HOME" ]; then
  if [ -d "/Applications/Android Studio.app/Contents/jbr/Contents/Home" ]; then
    export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
  elif command -v /usr/libexec/java_home >/dev/null 2>&1; then
    JAVA_HOME="$(/usr/libexec/java_home 2>/dev/null || true)"
    if [ -n "$JAVA_HOME" ]; then
      export JAVA_HOME
    fi
  fi
fi

if [ -z "$JAVA_HOME" ]; then
  echo "Java not found. Install Android Studio or set JAVA_HOME to a JDK 17+ install."
  exit 1
fi

KEYTOOL="$JAVA_HOME/bin/keytool"
KEYSTORE_FILE="$ANDROID_DIR/release.keystore"
KEYSTORE_PROPS="$ANDROID_DIR/keystore.properties"
KEY_ALIAS="bulk-messanger"

ensure_release_signing() {
  if [ -f "$KEYSTORE_PROPS" ] && [ -f "$KEYSTORE_FILE" ]; then
    return 0
  fi

  echo "No release keystore found — creating a local signing key for sideload installs..."
  echo "(Do not use this auto-generated key for Play Store uploads.)"

  # Stable-enough local password; stored next to the keystore (android/ is gitignored).
  STORE_PASS="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
  KEY_PASS="$STORE_PASS"

  "$KEYTOOL" -genkeypair \
    -v \
    -storetype PKCS12 \
    -keystore "$KEYSTORE_FILE" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -storepass "$STORE_PASS" \
    -keypass "$KEY_PASS" \
    -dname "CN=Bulk Messanger, OU=Mobile, O=BulkMessanger, L=Local, ST=Local, C=US"

  # storeFile is resolved relative to apps/mobile/android/app/
  cat > "$KEYSTORE_PROPS" <<EOF
storeFile=../release.keystore
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASS
EOF

  echo "Created:"
  echo "  $KEYSTORE_FILE"
  echo "  $KEYSTORE_PROPS"
}

cd "$ANDROID_DIR"

if [ "$VARIANT" = "debug" ]; then
  ./gradlew assembleDebug
  APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
else
  ensure_release_signing

  # Make sure Gradle picks up signing even if build.gradle was regenerated by Cap.
  if ! grep -q 'keystore.properties' app/build.gradle 2>/dev/null; then
    echo "WARNING: app/build.gradle has no keystore.properties signing block."
    echo "Release signing may not apply. Re-check Capacitor Android templates."
  fi

  ./gradlew assembleRelease

  if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
    APK_PATH="app/build/outputs/apk/release/app-release.apk"
  elif [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
    echo ""
    echo "ERROR: Release APK is unsigned — phones will refuse to install it."
    echo "Expected signing via $KEYSTORE_PROPS"
    echo "Built file: $(pwd)/app/build/outputs/apk/release/app-release-unsigned.apk"
    exit 1
  else
    echo "ERROR: No release APK found under app/build/outputs/apk/release/"
    ls -la app/build/outputs/apk/release/ 2>/dev/null || true
    exit 1
  fi
fi

ABS_APK="$(pwd)/$APK_PATH"

echo ""
echo "APK built:"
echo "  $ABS_APK"
echo ""
echo "Install on a connected device:"
echo "  adb install -r \"$ABS_APK\""
echo ""
echo "Or copy the APK to your phone and open it (enable Install unknown apps)."
